// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketMaster.Data;

#nullable disable

namespace TicketMaster.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250812075648_add inv wise image path")]
    partial class addinvwiseimagepath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("TicketMaster.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InviterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issued")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UniqCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("TicketMaster.Models.InvitationWithPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoordinateX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InvitationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Issued")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InvitationsWithPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
