// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TicketMaster.Data;

#nullable disable

namespace TicketMaster.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TicketMaster.Models.ApplicationSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FrontSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("application_settings", (string)null);
                });

            modelBuilder.Entity("TicketMaster.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedTicketsCount")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("EventDate")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxTickets")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("TicketMaster.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvitationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InviterName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Issued")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Issued");

                    b.ToTable("invitations", (string)null);
                });

            modelBuilder.Entity("TicketMaster.Models.InvitationWithPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoordinateX")
                        .HasColumnType("integer");

                    b.Property<int>("CoordinateY")
                        .HasColumnType("integer");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvitationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Issued")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("invitations_with_point", (string)null);
                });

            modelBuilder.Entity("TicketMaster.Models.Issued", b =>
                {
                    b.Property<string>("UserCode")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserCode");

                    b.HasIndex("UserId");

                    b.ToTable("issueds", (string)null);
                });

            modelBuilder.Entity("TicketMaster.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Tickets",
                            Code = "tickets.manage",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create, view, edit, and delete tickets",
                            Name = "Manage Tickets"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Tickets",
                            Code = "tickets.view",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View tickets only",
                            Name = "View Tickets"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Events",
                            Code = "events.manage",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create, view, edit, and delete events",
                            Name = "Manage Events"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Events",
                            Code = "events.view",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View events only",
                            Name = "View Events"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Users",
                            Code = "users.manage",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create, view, edit, and delete users",
                            Name = "Manage Users"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Designs",
                            Code = "designs.manage",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Upload and manage invitation designs",
                            Name = "Manage Designs"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Issuers",
                            Code = "issuers.manage",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create and manage issuers",
                            Name = "Manage Issuers"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Reports",
                            Code = "reports.view",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View and export reports",
                            Name = "View Reports"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Settings",
                            Code = "settings.manage",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage application settings",
                            Name = "Manage Settings"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Tickets",
                            Code = "invitations.verify",
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Search and verify invitation codes",
                            Name = "Verify Invitations"
                        });
                });

            modelBuilder.Entity("TicketMaster.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Can manage tickets and events",
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Can view and create tickets",
                            Name = "Operator"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Can only search and verify invitation codes",
                            Name = "Checker"
                        });
                });

            modelBuilder.Entity("TicketMaster.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 1,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 12,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 6,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 7,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 8,
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 2,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 17,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 4,
                            RoleId = 3
                        },
                        new
                        {
                            Id = 18,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionId = 10,
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("TicketMaster.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            FirstName = "System",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Administrator",
                            Password = "$2a$11$k9Vm4Rbs46A..TH6lXiHsuMcEu/UaEDwZqpWRhtmClre5012CuYXu"
                        });
                });

            modelBuilder.Entity("TicketMaster.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedAt = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TicketMaster.Models.Invitation", b =>
                {
                    b.HasOne("TicketMaster.Models.Event", "Event")
                        .WithMany("Invitations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TicketMaster.Models.Issued", "IssuedUser")
                        .WithMany("Invitations")
                        .HasForeignKey("Issued")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("IssuedUser");
                });

            modelBuilder.Entity("TicketMaster.Models.Issued", b =>
                {
                    b.HasOne("TicketMaster.Models.User", null)
                        .WithMany("Issueds")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TicketMaster.Models.RolePermission", b =>
                {
                    b.HasOne("TicketMaster.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketMaster.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TicketMaster.Models.UserRole", b =>
                {
                    b.HasOne("TicketMaster.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketMaster.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketMaster.Models.Event", b =>
                {
                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("TicketMaster.Models.Issued", b =>
                {
                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("TicketMaster.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TicketMaster.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TicketMaster.Models.User", b =>
                {
                    b.Navigation("Issueds");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
